Update buildspec.yml

diff --git a/backend/buildspec.yml b/backend/buildspec.yml
--- a/backend/buildspec.yml
+++ b/backend/buildspec.yml
@@ -52,11 +52,12 @@ phases:
       - echo "Performing DNS resolution test..."
       - nslookup $DB_HOST || echo "DNS resolution failed for DB_HOST: $DB_HOST"
       - echo "Attempting connection to database..."
-      - if nc -zv $DB_HOST $DB_PORT; then
-          echo "Successfully connected to the database.";
+      - |
+        if nc -zv $DB_HOST $DB_PORT; then
+          echo "Successfully connected to the database."
         else
-          echo "Failed to connect to DB_HOST: $DB_HOST on port $DB_PORT";
-          exit 1;
+          echo "Failed to connect to DB_HOST: $DB_HOST on port $DB_PORT"
+          exit 1
         fi
       - echo "Current .env file contents:"
       - cat $CODEBUILD_SRC_DIR/backend/.env
